### ISSUE TITLE
no license present

### ISSUE THREAD

**Issue by DepuydtLore** [U-Ar/full-br-index#9]
Hi

Would it be possible to add a license to this repository? 

Best regards,
Lore Depuydt

**Comment by U-Ar** [comment]
Since this project is dependent on the Big-BWT project (https://gitlab.com/manzai/Big-BWT), it is difficult to add a license to this project unless that project's license is explicitly stated. I'd appreciate it if you could first make a request to the Big-BWT Project.

**Comment by DepuydtLore** [comment]
A [GNU GPLv3 license](https://gitlab.com/manzai/Big-BWT/-/blob/master/LICENSE) was just added to the Big-BWT library.

**Comment by U-Ar** [comment]
Thank you for your prompt action.
I've also adopted the GPLv3 license for this project.
https://github.com/U-Ar/full-br-index/commit/182e0942722c48b1e77b5c9fd0e95cd2fcd6dbde

**Comment by DepuydtLore** [comment]
Thank you!
